const audio=document.getElementById('audio'),content=document.getElementById('content'),fileInput=document.getElementById('fileInput'),importBtn=document.getElementById('importBtn'),searchInput=document.getElementById('searchInput'),playBtn=document.getElementById('playBtn'),progress=document.getElementById('progress'),volume=document.getElementById('volume'),currentTime=document.getElementById('currentTime'),duration=document.getElementById('duration'),playerTitle=document.getElementById('playerTitle'),playerArtist=document.getElementById('playerArtist'),playerCover=document.getElementById('playerCover');
let tracks=JSON.parse(localStorage.getItem('music-tracks')||'[]'),index=-1,shuffled=false,repeating=false,favorites=new Set(JSON.parse(localStorage.getItem('music-favorites')||'[]'));
const demo=[{title:'Midnight City',artist:'M83',album:'Hurry Up, We’re Dreaming',cover:'https://images.unsplash.com/photo-1516280440614-37939bbacd81?auto=format&fit=crop&w=600&q=80'},{title:'After Dark',artist:'Mr.Kitty',album:'Time',cover:'https://images.unsplash.com/photo-1493225457124-a3eb161ffa5f?auto=format&fit=crop&w=600&q=80'},{title:'Sunset Lover',artist:'Petit Biscuit',album:'Presence',cover:'https://images.unsplash.com/photo-1506157786151-b8491531f063?auto=format&fit=crop&w=600&q=80'}];
function esc(s){return String(s).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));}
function save(){localStorage.setItem('music-tracks',JSON.stringify(tracks.map(t=>({...t,url:t.local?undefined:t.url}))));localStorage.setItem('music-favorites',JSON.stringify([...favorites]));}
function fmt(sec){return Number.isFinite(sec)?Math.floor(sec/60)+':'+String(Math.floor(sec%60)).padStart(2,'0'):'0:00';}
function cover(t){return t.cover||'https://images.unsplash.com/photo-1516280440614-37939bbacd81?auto=format&fit=crop&w=600&q=80';}
function render(view='listen',query=''){
 let list=tracks.length?tracks:demo,q=query.toLowerCase();
 if(view==='favorites')list=list.filter((t)=>favorites.has(tracks.indexOf(t))); if(view==='recent')list=list.slice().reverse(); if(view==='online')list=list.filter(t=>t.online); if(q)list=list.filter(t=>(t.title+' '+t.artist+' '+t.album).toLowerCase().includes(q));
 const cards=list.slice(0,8).map(t=>`<div class="album" data-track="${tracks.indexOf(t)}"><div class="cover"><img src="${cover(t)}" alt=""></div><strong>${esc(t.title)}</strong><span>${esc(t.artist)}</span></div>`).join('');
 const songs=list.map(t=>{const real=tracks.indexOf(t);return `<div class="song" data-track="${real}"><img class="song-cover" src="${cover(t)}"><div><div class="song-name">${esc(t.title)}</div><div class="song-artist">${esc(t.artist)} · ${esc(t.album||'Online')}</div></div><button class="song-heart" data-fav="${real}">${favorites.has(real)?'♥':'♡'}</button><span class="song-time">${t.online?'ONLINE':'♪'}</span></div>`}).join('');
 if(!tracks.length)content.innerHTML=`<div class="hero"><div><div class="eyebrow">MUSIC PLAYER</div><h1>Âm nhạc, theo cách của bạn.</h1><p>Phát nhạc từ máy hoặc thêm URL audio online hợp pháp.</p><button class="import-btn" id="heroImport">Thêm nhạc từ máy</button><button class="import-btn" id="heroOnline">＋ Nhạc Online</button></div></div><div class="section-title"><h2>Khám phá</h2><span class="muted">Demo artwork</span></div><div class="album-grid">${demo.map((t,i)=>`<div class="album" data-demo="${i}"><div class="cover"><img src="${cover(t)}"></div><strong>${t.title}</strong><span>${t.artist}</span></div>`).join('')}</div>`;
 else content.innerHTML=`<div class="section-title"><h2>${view==='favorites'?'Bài hát yêu thích':view==='recent'?'Phát gần đây':view==='browse'?'Duyệt nhạc':view==='library'?'Thư viện':view==='online'?'Nhạc Online':'Nghe ngay'}</h2><span class="muted">${list.length} bài hát</span></div><div class="album-grid">${cards}</div><div class="section-title"><h2>Tất cả bài hát</h2></div><div class="song-list">${songs||'<div class="empty">Không có bài hát phù hợp.</div>'}</div>`;
 document.getElementById('heroImport')?.addEventListener('click',()=>fileInput.click());document.getElementById('heroOnline')?.addEventListener('click',openOnline);
 content.querySelectorAll('[data-track]').forEach(el=>el.addEventListener('click',e=>{if(e.target.closest('[data-fav]'))return;const n=Number(el.dataset.track);if(n>=0)load(n,true);}));
 content.querySelectorAll('[data-demo]').forEach(el=>el.addEventListener('click',()=>alert('Demo artwork chỉ để xem giao diện.')));
 content.querySelectorAll('[data-fav]').forEach(b=>b.addEventListener('click',e=>{e.stopPropagation();const n=Number(b.dataset.fav);favorites.has(n)?favorites.delete(n):favorites.add(n);save();render(view,searchInput.value);}));
}
function load(n,autoplay=false){if(n<0||n>=tracks.length)return;index=n;const t=tracks[n];audio.src=t.url;playerTitle.textContent=t.title;playerArtist.textContent=t.artist||'Unknown Artist';playerCover.classList.remove('placeholder');playerCover.innerHTML=`<img src="${cover(t)}" alt="">`;if(autoplay)audio.play().catch(()=>alert('Không thể phát URL này. Hãy kiểm tra URL có trỏ trực tiếp tới file audio và cho phép CORS.'));updatePlay();}
function updatePlay(){playBtn.textContent=audio.paused?'▶':'Ⅱ';}
function openOnline(){document.getElementById('onlineModal').hidden=false;document.getElementById('onlineUrl').focus();}
function closeOnline(){document.getElementById('onlineModal').hidden=true;}
importBtn.onclick=()=>fileInput.click();document.getElementById('onlineBtn').onclick=openOnline;document.getElementById('closeOnline').onclick=closeOnline;document.getElementById('cancelOnline').onclick=closeOnline;
document.getElementById('addOnline').onclick=()=>{const url=document.getElementById('onlineUrl').value.trim(),title=document.getElementById('onlineTitle').value.trim()||'Bài hát Online',artist=document.getElementById('onlineArtist').value.trim()||'Online Artist',coverUrl=document.getElementById('onlineCover').value.trim();if(!/^https?:\/\//i.test(url)){alert('Hãy nhập URL http/https hợp lệ.');return;}tracks.push({title,artist,album:'Online Music',cover:coverUrl||'https://images.unsplash.com/photo-1516280440614-37939bbacd81?auto=format&fit=crop&w=600&q=80',url,online:true});save();const n=tracks.length-1;closeOnline();['onlineUrl','onlineTitle','onlineArtist','onlineCover'].forEach(id=>document.getElementById(id).value='');render('online');load(n,true);};
fileInput.onchange=e=>{[...e.target.files].forEach(file=>{tracks.push({title:file.name.replace(/\.[^/.]+$/,''),artist:'Tệp của bạn',album:'Local Music',cover:'https://images.unsplash.com/photo-1516280440614-37939bbacd81?auto=format&fit=crop&w=600&q=80',url:URL.createObjectURL(file),local:true});});save();render();if(index<0&&tracks.length)load(tracks.length-e.target.files.length,false);fileInput.value='';};
playBtn.onclick=()=>{if(index<0){if(tracks.length)load(0,true);return;}audio.paused?audio.play():audio.pause();updatePlay();};
document.getElementById('prevBtn').onclick=()=>{if(tracks.length){index=(index-1+tracks.length)%tracks.length;load(index,true)}};document.getElementById('nextBtn').onclick=()=>{if(tracks.length){load(shuffled?Math.floor(Math.random()*tracks.length):(index+1)%tracks.length,true)}};
document.getElementById('shuffleBtn').onclick=()=>{shuffled=!shuffled;document.getElementById('shuffleBtn').style.color=shuffled?'#fff':''};document.getElementById('repeatBtn').onclick=()=>{repeating=!repeating;audio.loop=repeating;document.getElementById('repeatBtn').style.color=repeating?'#fff':''};
document.getElementById('likeBtn').onclick=()=>{if(index<0)return;favorites.has(index)?favorites.delete(index):favorites.add(index);save();document.getElementById('likeBtn').textContent=favorites.has(index)?'♥':'♡';render();};
volume.oninput=()=>audio.volume=volume.value;audio.volume=.8;progress.oninput=()=>{if(audio.duration)audio.currentTime=progress.value/100*audio.duration};audio.ontimeupdate=()=>{progress.value=audio.duration?audio.currentTime/audio.duration*100:0;currentTime.textContent=fmt(audio.currentTime);duration.textContent=fmt(audio.duration)};audio.onloadedmetadata=()=>duration.textContent=fmt(audio.duration);audio.onplay=updatePlay;audio.onpause=updatePlay;audio.onended=()=>{if(!repeating)document.getElementById('nextBtn').click()};
searchInput.oninput=()=>render('listen',searchInput.value);document.querySelectorAll('.nav-item').forEach(btn=>btn.onclick=()=>{document.querySelectorAll('.nav-item').forEach(x=>x.classList.remove('active'));btn.classList.add('active');render(btn.dataset.view,searchInput.value)});document.getElementById('createPlaylist').onclick=()=>{const name=prompt('Tên playlist mới:');if(name)alert(`Đã tạo playlist “${name}” (giao diện demo).`)};render();